### PR TITLE
Session system

### PR DESCRIPTION
**Pull request by iapellaniz**
This PR will add a basic user system and some other related features:

- Log in & log out button in the app menu bar
- Window closing based on current permission level
- Code cleanup, and various refactors (thanks Iker!) related to DAO and client-server communication

### CODE REVIEW

**Review by iker-barriocanal — CHANGES_REQUESTED** [review]
Getting an error launching server:
```
21:11:42,489 (es.deusto.spq.server.Server.main()) DEBUG [ServerLog] - IHotelManager initialized. Rebinding...
21:11:42,680 (es.deusto.spq.server.Server.main()) FATAL [ServerLog] - RMI error. Turning off... - Error occurred in server thread; nested exception is:
        java.lang.NoClassDefFoundError: java/sql/Timestamp
java.rmi.ServerError: Error occurred in server thread; nested exception is:
        java.lang.NoClassDefFoundError: java/sql/Timestamp
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:388)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
        at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
        at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:375)
        at java.rmi/sun.rmi.registry.RegistryImpl_Stub.rebind(RegistryImpl_Stub.java:155)
        at java.rmi/java.rmi.Naming.rebind(Naming.java:177)
        at es.deusto.spq.server.Server.initializeServer(Server.java:34)
        at es.deusto.spq.server.Server.main(Server.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NoClassDefFoundError: java/sql/Timestamp
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3172)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3197)
        at java.base/java.lang.Class.getMethods(Class.java:1910)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Proxy.java:710)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:622)
        at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:425)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:423)
        at java.base/java.lang.reflect.Proxy.getProxyClass(Proxy.java:383)
        at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:699)
        at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:688)
        at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:611)
        at java.rmi/java.rmi.server.RMIClassLoader$2.loadProxyClass(RMIClassLoader.java:646)
        at java.rmi/java.rmi.server.RMIClassLoader.loadProxyClass(RMIClassLoader.java:311)
        at java.rmi/sun.rmi.server.MarshalInputStream.resolveProxyClass(MarshalInputStream.java:254)
        at java.base/java.io.ObjectInputStream.readProxyDesc(ObjectInputStream.java:1818)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1769)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
        at java.rmi/sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:135)
        at java.rmi/sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:467)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:297)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: java.sql.Timestamp
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.rmi/sun.rmi.server.LoaderHandler$Loader.loadClass(LoaderHandler.java:1207)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 37 more
```

**Comment by iapellaniz** [comment]
> Getting an error launching server:
> 
> ```
> 21:11:42,489 (es.deusto.spq.server.Server.main()) DEBUG [ServerLog] - IHotelManager initialized. Rebinding...
> 21:11:42,680 (es.deusto.spq.server.Server.main()) FATAL [ServerLog] - RMI error. Turning off... - Error occurred in server thread; nested exception is:
>         java.lang.NoClassDefFoundError: java/sql/Timestamp
> java.rmi.ServerError: Error occurred in server thread; nested exception is:
>         java.lang.NoClassDefFoundError: java/sql/Timestamp
>         at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:388)
>         at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
>         at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
>         at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:835)
>         at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
>         at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
>         at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:375)
>         at java.rmi/sun.rmi.registry.RegistryImpl_Stub.rebind(RegistryImpl_Stub.java:155)
>         at java.rmi/java.rmi.Naming.rebind(Naming.java:177)
>         at es.deusto.spq.server.Server.initializeServer(Server.java:34)
>         at es.deusto.spq.server.Server.main(Server.java:27)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
>         at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
>         at java.base/java.lang.Thread.run(Thread.java:835)
> Caused by: java.lang.NoClassDefFoundError: java/sql/Timestamp
>         at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
>         at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3172)
>         at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3197)
>         at java.base/java.lang.Class.getMethods(Class.java:1910)
>         at java.base/java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Proxy.java:710)
>         at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:622)
>         at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:425)
>         at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
>         at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
>         at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:423)
>         at java.base/java.lang.reflect.Proxy.getProxyClass(Proxy.java:383)
>         at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:699)
>         at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:688)
>         at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:611)
>         at java.rmi/java.rmi.server.RMIClassLoader$2.loadProxyClass(RMIClassLoader.java:646)
>         at java.rmi/java.rmi.server.RMIClassLoader.loadProxyClass(RMIClassLoader.java:311)
>         at java.rmi/sun.rmi.server.MarshalInputStream.resolveProxyClass(MarshalInputStream.java:254)
>         at java.base/java.io.ObjectInputStream.readProxyDesc(ObjectInputStream.java:1818)
>         at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1769)
>         at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
>         at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
>         at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
>         at java.rmi/sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:135)
>         at java.rmi/sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:467)
>         at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:297)
>         at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
>         at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
>         at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
>         at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         ... 1 more
> Caused by: java.lang.ClassNotFoundException: java.sql.Timestamp
>         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
>         at java.rmi/sun.rmi.server.LoaderHandler$Loader.loadClass(LoaderHandler.java:1207)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
>         ... 37 more
> ```

Sorry, can't reproduce. It's working fine for me :S
Let's see if someone else has the same problem

**Review by Egoes98 — CHANGES_REQUESTED** [review]
I also get the error.

> [INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ HotelManagement ---
23:05:08,467 (es.deusto.spq.server.Server.main()) DEBUG [ServerLog] - IHotelManager initialized. Rebinding...
23:05:08,576 (es.deusto.spq.server.Server.main()) FATAL [ServerLog] - RMI error. Turning off... - Error occurred in server thread; nested exception is:
        java.lang.NoClassDefFoundError: java/sql/Timestamp
java.rmi.ServerError: Error occurred in server thread; nested exception is:
        java.lang.NoClassDefFoundError: java/sql/Timestamp
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:388)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
        at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
        at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:375)
        at java.rmi/sun.rmi.registry.RegistryImpl_Stub.rebind(RegistryImpl_Stub.java:155)
        at java.rmi/java.rmi.Naming.rebind(Naming.java:177)
        at es.deusto.spq.server.Server.initializeServer(Server.java:34)
        at es.deusto.spq.server.Server.main(Server.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NoClassDefFoundError: java/sql/Timestamp
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3172)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3197)
        at java.base/java.lang.Class.getMethods(Class.java:1910)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Proxy.java:710)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:622)
        at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:425)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:423)
        at java.base/java.lang.reflect.Proxy.getProxyClass(Proxy.java:383)
        at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:699)
        at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:688)
        at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:611)
        at java.rmi/java.rmi.server.RMIClassLoader$2.loadProxyClass(RMIClassLoader.java:646)
        at java.rmi/java.rmi.server.RMIClassLoader.loadProxyClass(RMIClassLoader.java:311)
        at java.rmi/sun.rmi.server.MarshalInputStream.resolveProxyClass(MarshalInputStream.java:254)
        at java.base/java.io.ObjectInputStream.readProxyDesc(ObjectInputStream.java:1818)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1769)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
        at java.rmi/sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:151)
        at java.rmi/sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:468)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:298)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: java.sql.Timestamp
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.rmi/sun.rmi.server.LoaderHandler$Loader.loadClass(LoaderHandler.java:1207)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 37 more<

**Comment by iapellaniz** [comment]
@iker-barriocanal I need help with this one

**Pull request closed without merging**
